
POST http://localhost:3000/api/comments/new HTTP/1.1
Content-Type: application/json

{
  "publicationId": "57a633c4-25fc-43d7-9a9c-7e852fd3cd9b",
  "commentText": "далпиадл дплжвапжвп 4зщкеп"
}

###

GET http://localhost:3000/api/comments/57a633c4-25fc-43d7-9a9c-7e852fd3cd9b HTTP/1.1

###

DELETE http://localhost:3000/api/comments/e420e062-473f-43bc-8ed3-f6c0ec4d37e7 HTTP/1.1
Content-Type: application/json

###
