
POST http://localhost:3000/api/post/new HTTP/1.1
Content-Type: application/json

{
  "photo": 8,  
  "type": "photo"
}

###

GET http://localhost:3000/api/post/51a76b43-d9b9-4c94-bbba-d08a078c5c70 HTTP/1.1

###

DELETE http://localhost:3000/api/post/caf84897-2833-4e56-b8be-2f8b65e87011 HTTP/1.1

###

PATCH http://localhost:3000/api/post/0b35d5ab-2fd6-45f1-bbf2-810f5b9e8541 HTTP/1.1
Content-Type: application/json

{
  "quoteText": "второй раз переписанная цитата",
  "quoteAuthor": "автор все тот же",
  "type": "quote"
}

###

GET http://localhost:3000/api/post HTTP/1.1

###


PATCH http://localhost:3000/api/post/3d372824-533e-4f3d-9d26-0c2456faf47f/change-likes HTTP/1.1
Content-Type: application/json

{
  "likesCountChange": -1
}