
POST http://localhost:3000/api/post/new HTTP/1.1
Content-Type: application/json

{
  "quoteText": "какая-то очень древняя и очень мудрая мысль",
  
 
  "type": "quote"
}

###

GET http://localhost:3000/api/post/b736b8bc-dbc8-4aec-8e0f-09e775559b67 HTTP/1.1

###