# Create a new user
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "strangeuser3@mail.com",
  "name": "Natasha",
  "password": "1234567"
}

###

# Get user by ID
GET http://localhost:3000/api/user/66bcca071a0ba64bdf10dc0e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0cmFuZ2V1c2VyMkBtYWlsLmNvbSIsIm5hbWUiOiJLYXR5YSIsImlhdCI6MTcyNDY5NzQ4MiwiZXhwIjoxNzI0Njk3NzgyfQ.hRl3uZKnrcafZ7mS-MvonERKFCW7PRC6OfxjWVx1Wbo

###

# Login user by email and password
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "strangeuser2@mail.com",
  "password": "1234567"
}

###